### ISSUE TITLE
Feature request: dynamic parameter handling

### ISSUE THREAD

**Issue by bmaupin** [anishathalye/proof-html#1]
Hi,

For a while I'd been using this action instead: https://github.com/chabad360/htmlproofer

However, that action isn't pinned to a specific version of htmlproofer so it keeps breaking due to breaking changes upstream.

I like how this GitHub Action is pinned to a specific version of htmlproofer (even if it's an old one), however I noticed that there are only options for a limited number of CLI parameters.

For example, here are some of the parameters I need that this action doesn't provide as options:

- `assume_extension`
- `disable-external`
- `url-swap`

The simplest approach might be to add those missing options, but instead my proposal would be to add dynamic parameter handling, which is used by the aforementioned action (https://github.com/chabad360/htmlproofer). If you look there, it looks like they accept all arguments to htmlproofer as one option (`arguments`): https://github.com/chabad360/htmlproofer/blob/master/action.yml#L9

... and then they parse those in the entrypoint using `xargs`: https://github.com/chabad360/htmlproofer/blob/84d8858062ae9927f3ce73dcaa29c496b159f092/entrypoint.sh#L7

This seems much more future-proof because htmlproofer has gone through several breaking changes to the parameters, and much less work to maintain for this project.

In the meantime I've come up with a workaround:

```yaml
      - name: Check internal links using htmlproofer
        uses: anishathalye/proof-html@v1.4.0
        with:
          entrypoint: htmlproofer
          args: _site --assume_extension --disable-external --empty-alt-ignore --url-ignore "_,#" --url-swap "^/wiki:"
```

Thanks!
