### ISSUE TITLE
html-proofer seems to be run multiple times

### ISSUE THREAD

**Issue by franke-biosaxs** [anishathalye/proof-html#10]
Hi there. 

I've integrated the proof-html action into my deploy workflow and, after some trial-and-error got everything to work. Thanks for that!

However, I did notice that the output of html-proofer seems to come in triplicate, i.e. this is repeated three times:
> Running 4 checks (Images, Links, OpenGraph, Scripts) in ["./_site"] on *.html files ...
[snip errors]
HTML-Proofer found XXX failures!

The number of errors and error details are identical in each copy of the output. I can not say whether simply the output is echoed multiple times, or whether html-proofer is being run multiple times. It does not seem to have any negative impact besides a noisy log, though.

The workflow snippet:
```
      - name: Check URLs
        uses: anishathalye/proof-html@v2
        continue-on-error: true
        with:
          directory: ./_site
          enforce_https: true
          check_favicon: false
          tokens: |
            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"}
          ignore_url_re: |
            ^https://twitter.com/
          swap_urls: |
            {"^/atsas": ""}
```

Btw, the [README of html-proofer](https://github.com/gjtorikian/html-proofer) states:
> Also make sure that your later step which runs HTMLProofer will not return a failed shell status. You can try something like html-proof ... || true. Because a failed step in GitHub Actions will skip all later steps.

Which is exactly what happened for me until I added `continue-on-error: true`. Issue was, I ran into a loop-situation of html-proofer complaining about missing external files, which stopped the workflow that would have deployed those files in the first place. Took me a while to find, maybe you could add this option to your examples? Thanks!
